# Generated by Django 5.1.1 on 2024-09-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='course',
            table='Courses',
        ),
        migrations.AlterModelTable(
            name='group',
            table='Groups',
        ),
        migrations.AlterModelTable(
            name='task',
            table='Tasks',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
