# Generated by Django 5.1.1 on 2024-10-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect_app', '0003_task_assigned_groups_coursefile_studentprogress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_groups',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='students_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacherfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
