# Generated by Django 5.1.1 on 2024-10-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect_app', '0004_remove_task_assigned_groups_task_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
