# Generated by Django 5.1.1 on 2024-10-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect_app', '0006_alter_groupnumber_options_alter_groupnumber_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educonnect_app.groupnumber'),
        ),

    ]
